### ISSUE TITLE
bug 

### ISSUE THREAD

**Issue by crguezl** [ULL-ESIT-GRADOII-TFG/ghedsh#1]
La gema no funciona debido a que busca el fichero de configuración `.json` en un lugar fijo.
Además de eso aparecen en el código otras alusiones a ficheros en lugares inadecuados para cuando la gema esté en producción por cuanto probablemente ni siquiera existan o se tenga derechos de escritura en donde caigan. Por ejemplo, todas las que siguen en el fichero `system.rb`:

```ruby
def load_assig_db
    json = File.read('./lib/db/assignments.json')
    config=JSON.parse(json)
    #if config["Orgs"] == nil
      #return false
    #else
      return config
    #end
  end

  def save_config(data)
    File.write('./lib/configure/configure.json', data.to_json)
  end

  def save_db(data)
    File.write('./lib/db/assignments.json', data.to_json)
  end
```

**Comment by alu0100505023** [comment]
Error solucionado en commit 6713aa68b17e71bf40a78097a3f3442aa519f045
