### ISSUE TITLE
cambio de privacidad de un conjunto de repos

### ISSUE THREAD

**Issue by crguezl** [ULL-ESIT-GRADOII-TFG/ghedsh#13]
Cambiar la privacidad de todos los repos de un grupo, una asignación o que casan con una expresión regular

**Comment by alu0100505023** [comment]
He añadido una opcion para cambiar la privacidad dentro de un repositorio. Aun falta automatizar para que lo haga de manera grupal en asignaciones y grupos.

El comando en si es _private_ (por ahora espera como parametro "true" o "false") , ademas he añadido una opcion _info_ para poder ver la informacion de un repositorio dentro de el.
