### ISSUE TITLE
invitación masiva a los alus de una clase para que se hagan miembros de una organización

### ISSUE THREAD

**Issue by crguezl** [ULL-ESIT-GRADOII-TFG/ghedsh#33]
Funcionalidades:

1. Invitación masiva a los alus de una clase para que se hagan miembros de una organización
2. Al revés: sacar de la organización a un grupo
2. Invitaciones a outside-collaborators múltiples
3. Cambiar de forma masiva la privacidad de múltiples repos

**Comment by alu0100816167** [comment]
Hola Casiano, voy a comenzar con este issue. Primero me gustaría preguntarle algunas cosas (los números coinciden con los indicados en las funcionalidades):
1. Con "alus" significa que los alumnos pondrán en un fichero (JSON) por ejemplo sus IDs de GitHub y los añado masivamente?
3. Se refiere a invitar a outside-collaborators para ser members de la org, o añadir personas como outside-collaborator?
4. Cambiar repo a public/private?

**Comment by crguezl** [comment]
> Hola Casiano, voy a comenzar con este issue. Primero me gustaría preguntarle algunas cosas (los números coinciden con los indicados en las funcionalidades):
> 
> 1.Con "alus" significa que los alumnos pondrán en un fichero (JSON) por ejemplo sus IDs de GitHub y los añado masivamente?

La idea es que bien listándolos o bien a partir de un fichero se pueda invitar a un grupo de usuarios GH.

Algo como:

```
> invite member fulano mengano zutano
```

o bien:

```
> invite member from file chuchu
```

> 3.Se refiere a invitar a outside-collaborators para ser members de la org, o añadir personas como outside-collaborator?

Yo creo que los outside collaborators son gente que aparecen como collaborators en un repo de la organización pero no son miembros de la organización.

La versión actual (2018) de GH Classroom mete como *outside collabators* a los alus cuando aceptan una asignación. No los hace miembros, Mi necesidad este curso era entonces invitar a que fueran  miembros de la organización a todos los outside collaborators. Tener un comando así:
```
> people outside collaborators
fulano
mengano
zutano
```
y depues copiarlos e invitarlos
```
> invite member fulano mengano zutano
```
o bien copiarlos en un fichero e invitarlos desde fichero. Esto hubiera bastado.

> 4.Cambiar repo a public/private especificando el nombre con Regexp?

Si. Gracias!

**Comment by alu0100816167** [comment]
>  Mi necesidad este curso era entonces invitar a que fueran miembros de la organización a todos los outside collaborators.

Le parece buena solución un comando >`invite_outside_collaborators` que cuando se ejecuta dentro del contexto de una organización invite a todos los outside collaborators a ser miembros de la organización?

**Comment by alu0100816167** [comment]
En la rama `carlos-refactoring` he creado un directorio `file_templates` donde están (y estarán más) "plantillas" para hacer acciones desde fichero en aquellos comandos que lo permiten.

Actualmente se está utilizando esa estructura en los ficheros y los comandos funcionan correctamente.
¿Está de acuerdo con su estructura? Para realizar ahora las modificaciones si son necesarias.
