### ISSUE TITLE
Outside Collaborators GitHub API

### ISSUE THREAD

**Issue by crguezl** [ULL-ESIT-GRADOII-TFG/ghedsh#34]
> Por cierto, he estado un par de días atascado en un error que me apareció con el método outside_collaborators (y que antes no me aparecía), escribí un issue en octokit.rb https://github.com/octokit/octokit.rb/issues/1015 a ver si me proporcionaban información. Además, en la documentación oficial, en el apartado de See also: sale que la página no existe. Hay alguna página donde pueda ver información sobre los cambios en la API o algo así?

Parece que desde `curl` funciona con un token bueno:

```
[~/local/src/githubclassroom/clementeTFG/pruebas/octokit-examples(master)]$ curl https://api.github.com/orgs/ULL-ESIT-GRADOII-TFG/outside_collaborators?access_token=blahblahblah
[
  {
    "login": "ctc87",
    "id": 10723126,
    "avatar_url": "https://avatars0.githubusercontent.com/u/10723126?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/ctc87",
    "html_url": "https://github.com/ctc87",
    "followers_url": "https://api.github.com/users/ctc87/followers",
    "following_url": "https://api.github.com/users/ctc87/following{/other_user}",
    "gists_url": "https://api.github.com/users/ctc87/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/ctc87/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/ctc87/subscriptions",
    "organizations_url": "https://api.github.com/users/ctc87/orgs",
    "repos_url": "https://api.github.com/users/ctc87/repos",
    "events_url": "https://api.github.com/users/ctc87/events{/privacy}",
    "received_events_url": "https://api.github.com/users/ctc87/received_events",
    "type": "User",
    "site_admin": false
  }
]
```

**Comment by crguezl** [comment]
@alu0100816167 También funciona desde `Octokit` Ruby con este programa:
```
$ cat outside-collaborators.rb 
require 'octokit'
require 'json'

token = 'blahblah'

def login(token)
  begin
    user=Octokit::Client.new(:access_token =>token) #per_page:100
    #user.auto_paginate=true #show all pages of any query
  rescue
    puts "Oauth error"
  end
  return user
end

us = login(token)
if us!=nil
  puts "Login succesful as #{us.login}\n"
  #puts us.inspect
  #puts JSON.pretty_generate(JSON.parse(us.to_json))
  # Por cierto, he estado un par de días atascado en un error que me apareció con el método outside_collaborators (y que antes no me aparecía), escribí un issue en octokit.rb https://github.com/octokit/octokit.rb/issues/1015 a ver si me proporcionaban información. Además, en la documentación oficial, en el apartado de See also: sale que la página no existe. Hay alguna página donde pueda ver información sobre los cambios en la API o algo así?
  ocol = us.outside_collaborators('ULL-ESIT-GRADOII-TFG')
  puts ocol.inspect

end
binding.pry
```

Al ejecutar:

```
[~/local/src/githubclassroom/clementeTFG/pruebas/octokit-examples(master)]$ ruby outside-collaborators.rb 
Login succesful as crguezl
[{:login=>"ctc87", :id=>10723126, :avatar_url=>"https://avatars0.githubusercontent.com/u/10723126?v=4", :gravatar_id=>"", :url=>"https://api.github.com/users/ctc87", :html_url=>"https://github.com/ctc87", :followers_url=>"https://api.github.com/users/ctc87/followers", :following_url=>"https://api.github.com/users/ctc87/following{/other_user}", :gists_url=>"https://api.github.com/users/ctc87/gists{/gist_id}", :starred_url=>"https://api.github.com/users/ctc87/starred{/owner}{/repo}", :subscriptions_url=>"https://api.github.com/users/ctc87/subscriptions", :organizations_url=>"https://api.github.com/users/ctc87/orgs", :repos_url=>"https://api.github.com/users/ctc87/repos", :events_url=>"https://api.github.com/users/ctc87/events{/privacy}", :received_events_url=>"https://api.github.com/users/ctc87/received_events", :type=>"User", :site_admin=>false}]
outside-collaborators.rb:26:in `<main>': undefined method `pry' for #<Binding:0x007ff407893520> (NoMethodError)
```

**Comment by alu0100816167** [comment]
Tengo que revisarlo con atención, ahora mismo lo que me sale a mí es esto:

<img width="1066" alt="captura de pantalla 2018-05-15 a las 12 54 46" src="https://user-images.githubusercontent.com/14928093/40055372-9deae308-583f-11e8-9014-da1f5a47c139.png">

Y el error viene de esta sección del código:

<img width="661" alt="captura de pantalla 2018-05-15 a las 12 55 40" src="https://user-images.githubusercontent.com/14928093/40055391-b278414e-583f-11e8-851f-182e94f8ae40.png">

Podría hacer un clone y ejecutar con el contenido de la rama 'carlos-refactoring' para comprobar si es algún problema mío local?

**Comment by alu0100816167** [comment]
He cogido el script de ejemplo (incluso generé un token nuevo) y sin embargo mi salida es la siguiente:

<img width="1024" alt="captura de pantalla 2018-05-15 a las 13 14 39" src="https://user-images.githubusercontent.com/14928093/40056113-2f6f742c-5842-11e8-80ef-b53adacb3556.png">

**Comment by alu0100816167** [comment]
La única manera en la que he conseguido que funcione es haciendo un GET desde el módulo net/http de ruby:

<img width="1025" alt="captura de pantalla 2018-05-15 a las 17 53 12" src="https://user-images.githubusercontent.com/14928093/40071565-0d2351aa-5869-11e8-998b-305ce7a96152.png">

No obstante, me parece un comportamiento raro que pueda hacer un GET y desde el método de la API me esté dando error.

**Comment by alu0100816167** [comment]
Bueno después de estar investigando un buen rato, he revisado las releases de la gema octokit.rb (actual 4.9.0) y he actualizado la versión del `ghedsh.gemspec` (que era 3.8) con `s.add_dependency octokit', '~> 4.8'`. Parece que ya lo que solventado y el aspecto es el siguiente:

<img width="457" alt="captura de pantalla 2018-05-15 a las 18 34 51" src="https://user-images.githubusercontent.com/14928093/40073511-ec4cd4fa-586e-11e8-82a0-77c1d9bccaad.png">

**Comment by crguezl** [comment]
¡Estupendo!
