### ISSUE TITLE
new_eval alu100-eval /alu100/

### ISSUE THREAD

**Issue by crguezl** [ULL-ESIT-GRADOII-TFG/ghedsh#40]
Probando a crear un repo para evaluar a `ale`:
```
crguezl> ULL-ESIT-PL-1718> new_eval ale-eval /ale/i
Initialized empty Git repository in /private/tmp/ale/ale-eval/.git/
Cloning into '/private/tmp/ale/ale-eval/iaas-AlejandroLF'...
remote: Counting objects: 186, done.
...
```

El repo resultante tiene este aspecto:

```
[/tmp/ale/ale-eval(master)]$ ls -l
total 0
drwxr-xr-x  13 casiano  wheel  416  6 jun 09:35 Egg-en-Pegg-AlejandroLF
drwxr-xr-x  12 casiano  wheel  384  6 jun 09:35 OOP-AlejandroLF
drwxr-xr-x   3 casiano  wheel   96  6 jun 09:35 ale-eval
drwxr-xr-x  12 casiano  wheel  384  6 jun 09:35 tfa-AlejandroLF
```
Esto es, se ha incluído como submódulo el propio repo `ale-eval` porque casa con la regexp.

No sé si esto puede considerarse un bug o una característica de la que el usuario debería estar advertido

**Comment by alu0100816167** [comment]
Sí más bien es un bug. Revisaré esa parte para descartar el repo que casa con la regexp pero que se trata del propio 'super-repo'.

**Comment by alu0100816167** [comment]
Parece que ya está solucionado en la versión 2.2.2

**Comment by crguezl** [comment]
¡Thanks! 👍
