### ISSUE TITLE
undefined method `gsub' for nil:NilClass

### ISSUE THREAD

**Issue by crguezl** [ULL-ESIT-GRADOII-TFG/ghedsh#43]
try catch y controlar mensaje:
```
crguezl> ULL-ESIT-PL-1718> cd alberto
undefined method `gsub' for nil:NilClass
```
sustituir por algo como "can't execute command" o similar

**Comment by alu0100816167** [comment]
solucionado a partir de la versión `ghedsh v2.3.6`. Se muestra `Error while running cd command. Usage: cd <type> <Regexp|String>`
