### ISSUE TITLE
ghedsh eval scripts

### ISSUE THREAD

**Issue by crguezl** [ULL-ESIT-GRADOII-TFG/ghedsh#45]
@alu0100816167: Esta es una funcionalidad que no se si se quedará para un futuro TFG o consideras que es viable tener un borrador para tu tFG.

Se trata de escribir un paquete npm que contiene un script `grade-node` que complementa la funcionalidad de evaluación de ghedsh.

Esta es la forma de uso desde `ghedsh`:

```
crguezl> ULL-ESIT-PL-1718> new_eval ale-eval /ale/i
...
crguezl> ULL-ESIT-PL-1718> cd repo ale-eval 
...
crguezl> ULL-ESIT-PL-1718> foreach grade-node --teacher teacher-tests-dir  --output grade.test.md
... 
```

1. `grade-node` recibe como argumento un directorio ` teacher-tests-dir/ ` que contiene las pruebas privadas (en `mocha` u otro framework)  que ha escrito el profesor para la práctica
2. Para cada repo `grade-node` copia en el subdirectorio  `test/` del alumno los contenidos de ` teacher-tests-dir/ `  
    1. Recuerda que dentro de un `git submodule foreach`
    2.  ... The command has access to the  variables `$name, $path, $sha1 and $toplevel`: 
    3. `$name `is the name of the relevant submodule section in .gitmodules, `$path` is the name of the submodule directory relative to the superproject, `$sha1` is the commit as recorded in the superproject, and `$toplevel` is the absolute path to the top-level of the superproject. 
4. `grade-node` hace un `npm install`y si tiene éxito un `npm test` redirigiendo la salida a un fichero markdown `grade-test.md`  que queda en el repo del alumno

Ahora el profe si quiere puede hacer algo como:

```
crguezl> ULL-ESIT-PL-1718> foreach gh-issue --title 'Resultado de las pruebas' --input grade-test.md
... 
```
que ejecutaría otro script `gh-issue`  que enviaría los issues

**Comment by alu0100816167** [comment]
Me parece una funcionalidad bastante interesante. Le voy a dar un empujón a la memoria y seguramente me dará tiempo de tener un módulo de ejemplo.

**Comment by crguezl** [comment]
Cuando lo tengas  será la "repanocha". Haremos un vídeo para la presentación con el proceso de evaluación

**Comment by alu0100816167** [comment]
Estupendo!
